name: 'Checkstyle Code Scan'
description: 'Runs Checkstyle scanner'

inputs:
    github-token:
        required: true
        description: 'The github token to authenticate this action'
    fail-static_analysis_checkstyle_fail_on_violations:
        required: true
        description: 'Flag to fail or not the pipeline on checkstyle violations'
        default: 'true'
    static_analysis_checkstyle_skip:
        required: true
        description: 'Flag to skip the checkstyle validation step altogether'
        default: 'false'

runs:
    using: "composite"
    steps:
        -   name: Run checkstyle with maven
            if: ${{ inputs.static_analysis_checkstyle_skip != 'true' }}
            shell: bash
            run: |
                ./mvnw checkstyle:check -Dcheckstyle.failOnViolation="${{ inputs.fail-static_analysis_checkstyle_fail_on_violations }}"

        -   name: Upload SARIF to GitHub Security tab
            if: ${{ inputs.static_analysis_checkstyle_skip != 'true' }}
            uses: github/codeql-action/upload-sarif@v3
            with:
                sarif_file: target/checkstyle-result.sarif
                category: checkstyle
                token: ${{ inputs.github-token }}
