name: 'Build and test project with Maven'
description: 'Builds and test project'

runs:
    using: "composite"
    steps:
        -   name: Run maven verify phase
            shell: bash
            run: |
                echo "running ./mvnw verify" 
                ./mvnw verify
