name: 'Java Flow'
on:
    workflow_call:
        inputs:
            build_tool:
                required: true
                description: "build tool used by the project. Options are {Maven, Gradle, npm, sbt}. Only maven is valid momentarily."
                type: string
                default: 'maven'
            build_type:
                required: true
                description: 'final object type to be built by the pipeline. Options are {artifact, docker_image_jvm, docker_image_graal_native}. Default: artifact'
                type: string
                default: 'artifact'
            deploy_package:
                required: false
                description: "Flag to deploy a package to GH Registry"
                type: boolean
                default: false
            java_vendor:
                required: false
                description: 'Supported vendors: oracle (default), temurin and openjdk (via https://jdk.java.net/ download).'
                type: string
                default: 'oracle'
            java_version:
                required: false
                description: 'Java version'
                type: string
                default: '25'
            services_docker_in_docker:
                required: true
                description: "configures the pipeline as requiring a docker in docker setup, for 'test containers' for example"
                type: boolean
                default: false
            static_analysis_checkstyle_fail_on_violations:
                required: true
                description: 'Flag to fail or not the pipeline on checkstyle violations'
                type: boolean
                default: false
            static_analysis_checkstyle_skip:
                required: false
                description: 'Flag to skip the checkstyle validation step altogether'
                type: boolean
                default: false
            testing_options_skip:
                required: true
                description: 'skip all tests'
                type: boolean
                default: false
            versioning_version:
                required: false
                description: 'Manually setting a version'
                type: string

        secrets:
            PACKAGES_USER:
                required: true
                description: 'Packages user from workflow'
            PACKAGES_TOKEN_RW:
                required: true
                description: 'Packages token from workflow'
            GH_TOKEN:
                required: true
                description: 'The GitHub token from the calling workflow'

jobs:
    java-flow:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            security-events: write

        # we are currently only building artifacts and not docker images...
        # in time, we'll add the docker variations step
        steps:
            -   name: checkout
                uses: actions/checkout@v6.0.2

            -   name: Set up Java
                uses: bmc-anvil/.github/.github/actions/language/jvm/java/setup-java@main
                with:
                    java_version: ${{ inputs.java_version }}
                    java_vendor: ${{ inputs.java_vendor }}

            -   name: Set up Maven
                uses: bmc-anvil/.github/.github/actions/language/jvm/build_tools/maven/setup-maven@main
                with:
                    packages_user: ${{ secrets.PACKAGES_USER }}
                    packages_token: ${{ secrets.PACKAGES_TOKEN_RW }}

            -   name: Cache Maven dependencies
                uses: bmc-anvil/.github/.github/actions/language/jvm/build_tools/maven/cache@main

            -   name: Run Checkstyle
                uses: bmc-anvil/.github/.github/actions/language/jvm/build_tools/maven/static-analysis/checkstyle@main
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    static_analysis_checkstyle_fail_on_violations: ${{ inputs.static_analysis_checkstyle_fail_on_violations }}
                    static_analysis_checkstyle_skip: ${{ inputs.static_analysis_checkstyle_skip }}

            -   name: Build and Test
                uses: bmc-anvil/.github/.github/actions/language/jvm/build_tools/maven/build-verify@main
                continue-on-error: true
                with:
                    github-token: ${{secrets.GITHUB_TOKEN}}

            -   name: Set up Version
                uses: bmc-anvil/.github/.github/actions/common/versioning@main
                with:
                    versioning_version: ${{ inputs.versioning_version }}
                if: ${{ inputs.deploy_package == true}}

            -   name: Set up Version in Build Tool
                uses: bmc-anvil/.github/.github/actions/language/jvm/build_tools/maven/setup-version@main
                if: ${{ inputs.deploy_package == true}}

            -   name: Deploy to Github Packages Registry
                uses: bmc-anvil/.github/.github/actions/language/jvm/build_tools/maven/deploy-package@main
                if: ${{ inputs.deploy_package == true}}
                with:
                    github-token: ${{ secrets.PACKAGES_TOKEN_RW }}